# Generated by Django 5.2.7 on 2025-11-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_hometext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hometext',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='hometext',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hometext',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='hometext',
            name='translation_key',
        ),
    ]
