# Generated by Django 5.2.7 on 2025-11-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_hometext_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='mastodon_url',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='mailto_url',
            field=models.URLField(blank=True, verbose_name='Mailto URL'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram URL'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='vk_url',
            field=models.URLField(blank=True, verbose_name='VK URL'),
        ),
    ]
