# Generated by Django 5.2.7 on 2025-11-09 07:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
